### ISSUE TITLE
Should we cover stateful hash based signatures

### ISSUE THREAD

**Issue by mprorock** [mesur-io/post-quantum-signatures#49] opened 2022-03-10 18:50 UTC
See [NIST SP 800-208](https://csrc.nist.gov/publications/detail/sp/800-208/final)

specifically HSS/LMS, XMSS and XMSS^mt

**Comment by OR13** [comment] 2022-03-10 19:06
I am tracking possible implementations that might be used to generate test vectors here: https://github.com/transmute-industries/verifiable-data/issues/180

**Comment by mprorock** [comment] 2022-03-14 14:14
good reference from [Panos](https://eprint.iacr.org/2017/349.pdf)

**Comment by OR13** [comment] 2022-03-21 14:08
LMS 
- https://github.com/gbanegas/sphss
- https://github.com/cisco/hash-sigs

**Comment by OR13** [comment] 2022-03-21 14:11
We should just translate the test vectors to JWK.

**Comment by OR13** [comment] 2022-03-26 22:33
I tried with LMS again, and again, no luck... I suggest we not consider registrations for LMS.

**Comment by OR13** [comment] 2022-04-03 13:59
I was able to get XMSS to sorta work, and build as an npm package... https://github.com/transmute-industries/xmss


The GoLang side of this is very rough, and I am not sure how correct it is since the original source only covers a single sign and verify cycle.

I suggest we close this issue out unless we can get 2 implementations and test vectors for both XMSS and LMS.

**Comment by OR13** [comment] 2022-04-03 14:37
I have put out a plea for help to COSE and CCG mailing lists: https://lists.w3.org/Archives/Public/public-credentials/2022Apr/0007.html

If we don't hear back in 2 weeks, I suggest we move LMS / XMSS out of scope, and refocus on the other schemes.

I don't think we should attempt any further work until multiple implementations and interoperable test vectors can be confirmed

**Comment by OR13** [comment] 2022-11-08 15:16
answer to issue title is no.

**Closed by OR13** 2022-11-08 15:16 UTC
